

export const foods = [
    { name: "Makaronilaatikko", categories: ["🍝", "🥩"], prepTime: 60 },
    { name: "Katkarapupasta", categories: ["🍝", "🐟"], prepTime: 30 },
    { name: "Pasta carbonara", categories: ["🍝", "🥩"], prepTime: 30 },
    { name: "Lihapullapasta", categories: ["🍝", "🥩"], prepTime: 15 },
    { name: "Jauheliha ja makaroni", categories: ["🍝", "🥩"], prepTime: 15 },
    { name: "Tonnikalapasta", categories: ["🍝", "🐟"], prepTime: 15 },
    { name: "Lohipasta", categories: ["🍝", "🐟"], prepTime: 30 },
    { name: "Lasagne/pikalasagne", categories: ["🍝", "🥩"], prepTime: 60 },
    { name: "Kanapasta", categories: ["🍝", "🐓"], prepTime: 30 },
    { name: "Lihapullat ja perunamuusi", categories: ["🥔", "🥩"], prepTime: 45 },
    { name: "Pinaattiletut ja perunamuusi", categories: ["🥔"], prepTime: 45 },
    { name: "Uunilohi + potut", categories: ["🥔", "🐟"], prepTime: 45 },
    { name: "Mureke ja perunat", categories: ["🥔", "🥩"], prepTime: 45 },
    { name: "Karjalanpaisti", categories: ["🥔", "🥩"], prepTime: 120 },
    { name: "Pihvi ja peruna", categories: ["🥔", "🥩"], prepTime: 45 },
    { name: "Kalaa pannulla ja potut", categories: ["🥔", "🐟"], prepTime: 30 },
    { name: "Kana ja ranskikset", categories: ["🥔", "🐓"], prepTime: 30 },
    { name: "Lohikeitto", categories: ["🐟","🥔"], prepTime: 45 },
    { name: "Savulohikeitto", categories: ["🐟","🥔"], prepTime: 45 },
    { name: "Lihakeitto", categories: ["🥩","🥔"], prepTime: 60 },
    { name: "Kasvissosekeitto", categories: ["🥔"], prepTime: 30 },
    { name: "Jauhelihakastike ja potut", categories: ["🥔", "🥩"], prepTime: 45 },
    { name: "Naudansuikaleet ja riisi", categories: ["🍚", "🥩"], prepTime: 30 },
    { name: "Jauheliha ja riisi", categories: ["🍚", "🥩"], prepTime: 30 },
    { name: "Kana ja riisi", categories: ["🍚", "🐓"], prepTime: 30 },
    { name: "Tortillat (jauheliha/kana/halloum)", categories: ["🥩"], prepTime: 15 },
    { name: "Kanasalaatti", categories: ["🐓"], prepTime: 15 },
    { name: "Riisipuuro ja soppa", categories: ["🍚"], prepTime: 45 },
    { name: "Mannapuuro", categories: [], prepTime: 15 },
    { name: "Possu ja riisi", categories: ["🍚", "🥩"], prepTime: 30 },
    { name: "Nachopelti", categories: ["🥩"], prepTime: 30 },
    { name: "Lämpimät leivät", categories: [], prepTime: 15 },
    { name: "Halloum pasta", categories: ["🍝"], prepTime: 30 },
    { name: "Pestopasta", categories: ["🍝"], prepTime: 15 },
    { name: "Pinaattikeitto", categories: ["🥔"], prepTime: 30 },
    { name: "Crispy kana", categories: ["🐓"], prepTime: 30 },
    { name: "Ristikkoperunat ja lihapullat", categories: ["🥔", "🥩"], prepTime: 45 },
    { name: "Pitsaa", categories: [], prepTime: 60 },
    { name: "Lohkoperunat ja kanaa tai pihviä", categories: ["🥔", "🐓"], prepTime: 45 },
    { name: "Quesedillat", categories: ["🥩"], prepTime: 30 },
    { name: "Kylmäsavulohipasta", categories: ["🍝", "🐟"], prepTime: 30 },
    { name: "Kana tikkamasala ja riisi", categories: ["🍚", "🐓"], prepTime: 45 },
    { name: "Kaalilaatikko", categories: ["🥩"], prepTime: 60 },
    { name: "Wingsit", categories: ["🥩"], prepTime: 30 },
    { name: "Hampurilaiset", categories: ["🥩"], prepTime: 45 },
    { name: "Pitat", categories: [], prepTime: 15 },
    { name: "Uunikana ja riisi", categories: ["🍚", "🐓"], prepTime: 45 },
    { name: "Pyttipannu", categories: ["🥔", "🥩"], prepTime: 30 },
    { name: "Chorizo pasta", categories: ["🍝", "🥩"], prepTime: 30 },
    { name: "Kinkkupiirakka", categories: ["🥩"], prepTime: 45 },
    { name: "Wok", categories: [], prepTime: 30 },
    { name: "Kinkkukiusaus", categories: ["🥔", "🥩"], prepTime: 45 },
    { name: "Pasta bolognese", categories: ["🍝", "🥩"], prepTime: 30 },
    { name: "Tortilla pitsa", categories: [], prepTime: 15 },
    { name: "Pasta salaatti", categories: ["🍝"], prepTime: 15 },
    { name: "Uunifetapasta", categories: ["🍝"], prepTime: 30 },
    { name: "Kvinoa-feta-salaatti", categories: [], prepTime: 30 },
    { name: "Wrapit (tonnikala/kana)", categories: ["🐟", "🥩", "🐓"], prepTime: 15 },
    { name: "Kanakeitto", categories: ["🐓","🥔"], prepTime: 45 },
    { name: "Täytetyt paprikat/kesäkurpitsat", categories: ["🥩"], prepTime: 45 },
    { name: "Hodarit", categories: ["🥩"], prepTime: 15 },
    { name: "Nuudelit (keitto)", categories: ["🍝"], prepTime: 15 },
    { name: "Uuniperunat", categories: ["🥔"], prepTime: 45 },
    { name: "Kalapuikot, perunamuusi ja kermaviilikastike", categories: ["🥔", "🐟"], prepTime: 45 },
    { name: "Paistettu riisi", categories: ["🍚"], prepTime: 30 },
    { name: "Nakkikeitto", categories: ["🥩","🥔"], prepTime: 45 },
    { name: "Kaalipekonisalaatti", categories: ["🥩"], prepTime: 15 },
    { name: "Turkkilainen pasta", categories: ["🍝"], prepTime: 30 },
  ];


